# Generated by Django 4.0.6 on 2022-08-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lon', models.FloatField(verbose_name='Долгота')),
                ('address', models.CharField(max_length=512, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'ГеоБаза',
                'verbose_name_plural': 'ГеоБаза',
            },
        ),
    ]
